### PR TITLE
2d array

### PR DESCRIPTION
**Pull request by priyankajainmodi**
2 D array

### CODE REVIEW

**Comment by priyankajainmodi** [comment]
[left rotation.txt](https://github.com/Bhawna11agg/Uplift-Project/files/4774727/left.rotation.txt)

**Comment by priyankajainmodi** [comment]
[sparse array.txt](https://github.com/Bhawna11agg/Uplift-Project/files/4774804/sparse.array.txt)

**Comment by Bhawna11agg** [comment]
Hey Priyanka!! pls update the repo by making new pull request don't make it in comments

**Comment by priyankajainmodi** [comment]
So mam shall I make new pull request for all the previous ques posted or
should I do it from next time onwards?

**Comment by Bhawna11agg** [comment]
Todays question that are left rotation and all

**Comment by priyankajainmodi** [comment]
Mam do we have to merge pull request?

**Comment by Bhawna11agg** [comment]
Hey!! just as you made your first pull request in as same way make for other questions also

**Comment by Bhawna11agg** [comment]
Nothing is different

**Comment by priyankajainmodi** [comment]
Mam now have pr made by me?

**Comment by Bhawna11agg** [comment]
No

**Comment by Bhawna11agg** [comment]
Hey listen! Go to create new file and paste your code there and then make PR

**Comment by Bhawna11agg** [comment]
Dont make anything on this page URL as this is your first PR that was merged so leave this makes it new

**Pull request merged**
