### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by radadiyamohit81**

### CODE REVIEW

**Comment by Bhawna11agg** [comment]
add that guessing game

**Comment by Bhawna11agg** [comment]
and also add screenshot of output of guessing game

**Comment by radadiyamohit81** [comment]
i already submitted guessing game on projects folder and can i upload the screenshot on the same folder or not?

**Comment by Bhawna11agg** [comment]
yes and update the readme as you make any game by a list of name of games

**Comment by radadiyamohit81** [comment]
I am not able to upload screenshot I don't know why..

**Comment by deepika-rana** [comment]
Were you able to generate the image URL?

**Comment by radadiyamohit81** [comment]
I just update my guessing file and adding the text of output instead of uploading image

**Comment by radadiyamohit81** [comment]
so merge my PR related to updating the file

**Comment by radadiyamohit81** [comment]
and closed this PR

**Pull request closed without merging**
