### PR TITLE
Create HackerRank -DS_Rakshith.NV

### PR DESCRIPTION
**Pull request by rakshithnv**

### CODE REVIEW

**Comment by rakshithnv** [comment]
#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;


int main() {
            int N;
            cin>>N;

            vector<int> arr(N);
            
            for (int i=0;i<N;i++)
                cin>>arr[i];

            reverse(arr.begin(),arr.end());

                for (int i=0;i<N;i++)
                cout<<arr[i]<<" ";

            return 0;
}

**Comment by Bhawna11agg** [comment]
Hey!! you have uploaded all the code in comments...it must not be in the comment.
In comments give the question name and code must be uploaded in correct position

**Comment by deepika-rana** [comment]
Also, the header files are not included. Make sure the code you upload is correctly running and formatted properly.

**Comment by deepika-rana** [comment]
Also, the header files are not included. Make sure the code you submit is running and formatted properly.

**Pull request closed without merging**
